schema_version = "1.0.0"

id = "squared_media_armory"
version = "0.0.1"
name = "Squared Media Armory"
tagline = "A Companion Addon to Squared Media Rig UI"
maintainer = "fxn-work@proton.me"
type = "add-on"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
# network = "Need to sync motion-capture data to server"
# files = "Import/export FBX from/to disk"
# clipboard = "Copy and paste bone transforms"